language: python
python:
- '3.8'
dist: xenial
services:
  - xvfb
before_install:
  - sudo apt-get install --force-yes freeglut3-dev
install:
- pip install .
- pip install pytest pytest-catchlog pytest-cov python-coveralls
script:
- cd tests
- pytest --cov kxg
after_success:
- coveralls
