language: python
python:
- '3.3'
- '3.4'
- '3.5'
- nightly
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
install:
- pip install .
- pip install pytest pytest-capturelog pytest-cov python-coveralls
script:
- py.test tests
- py.test tests --cov kxg
after_success:
- coveralls
