language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
install:
  - pip install .
script:
  - py.test tests/??_test_*.py
